FROM ontotext/graphdb:9.11.4-se as graphdb
ARG GRAPHDB_LICENSE_FILE
WORKDIR /opt/graphdb/home
COPY $GRAPHDB_LICENSE_FILE /opt/graphdb/home/conf/

COPY rulesets rulesets

COPY init-data graphdb-import
COPY init-config termit-repo-config
COPY repo-init.sh ${GRAPHDB_INSTALL_DIR}/repo-init.sh

EXPOSE 7200

CMD ${GRAPHDB_INSTALL_DIR}/repo-init.sh termit-repo-config ${GRAPHDB_HOME} & ${GRAPHDB_INSTALL_DIR}/bin/graphdb -Dgraphdb.home=${GRAPHDB_HOME}

