{
 "title": "TermIt state",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Request count and latency",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by(uri) (max_over_time(http_server_requests_seconds_max{uri!=\"/actuator/prometheus\"}[24h]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(uri) (increase(http_server_requests_seconds_count{uri!=\"/actuator/prometheus\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per user",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(user) (increase(app_user_requests_total[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{uri!=\"/actuator/prometheus\"}[5m]) * 60",
     "legendFormat": "{{method}} {{uri}} - {{status}}"
    }
   ]
  },
  {
   "title": "Avg request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{method=\"GET\", outcome=\"SUCCESS\", uri!=\"/actuator/prometheus\"}[24h]) / (rate(http_server_requests_seconds_count{method=\"GET\", outcome=\"SUCCESS\", uri!=\"/actuator/prometheus\"}[24h]))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "CPU usage" }
   ]
  },
  {
   "title": "Heap size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\"}",
     "legendFormat": "{{id}}"
    }
   ]
  }
 ]
}